# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicalGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('founded', models.DateField()),
                ('style', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('role', models.CharField(max_length=70)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gilp.MusicalGroupModel')),
            ],
        ),
    ]
