# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.DateField(null=True)),
                ('left', models.DateField(null=True)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='MusicalGroupModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=120, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'musicalgroup',
            },
        ),
        migrations.CreateModel(
            name='MusicianModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(null=True)),
                ('role', models.CharField(max_length=70, null=True)),
                ('group', models.ManyToManyField(through='gilp.MembershipModel', to='gilp.MusicalGroupModel')),
            ],
            options={
                'db_table': 'musician',
            },
        ),
        migrations.AddField(
            model_name='membershipmodel',
            name='musicalGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gilp.MusicalGroupModel'),
        ),
        migrations.AddField(
            model_name='membershipmodel',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gilp.MusicianModel'),
        ),
    ]
