# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-14 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gilp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(null=True)),
                ('role', models.CharField(max_length=70, null=True)),
            ],
            options={
                'db_table': 'musician',
            },
        ),
        migrations.RenameModel(
            old_name='MembershipModel',
            new_name='Membership',
        ),
        migrations.RenameModel(
            old_name='MusicalGroupModel',
            new_name='MusicalGroup',
        ),
        migrations.RemoveField(
            model_name='musicianmodel',
            name='group',
        ),
        migrations.AlterField(
            model_name='membership',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gilp.Musician'),
        ),
        migrations.DeleteModel(
            name='MusicianModel',
        ),
        migrations.AddField(
            model_name='musician',
            name='group',
            field=models.ManyToManyField(through='gilp.Membership', to='gilp.MusicalGroup'),
        ),
    ]
