# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gilp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicalgroupmodel',
            name='country',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='musicalgroupmodel',
            name='founded',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='musicalgroupmodel',
            name='style',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='gender',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gilp.MusicalGroupModel'),
        ),
        migrations.AlterField(
            model_name='musicianmodel',
            name='role',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
