# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-05 11:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('login', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'account',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.DateField(null=True)),
                ('left', models.DateField(null=True)),
            ],
            options={
                'db_table': 'membership',
            },
        ),
        migrations.CreateModel(
            name='MusicalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=120, null=True)),
                ('country', models.CharField(max_length=40, null=True)),
            ],
            options={
                'db_table': 'musicalgroup',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birth', models.DateField(null=True)),
                ('role', models.CharField(max_length=70, null=True)),
                ('group', models.ManyToManyField(through='gilp.Membership', to='gilp.MusicalGroup')),
            ],
            options={
                'db_table': 'musician',
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='musicalGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gilp.MusicalGroup'),
        ),
        migrations.AddField(
            model_name='membership',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gilp.Musician'),
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gilp.Musician'),
        ),
    ]
