# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-06 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilp', '0002_remove_account_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(max_length=50),
        ),
    ]
