# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gilp', '0003_auto_20180106_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='entered',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='left',
        ),
        migrations.AddField(
            model_name='musician',
            name='email',
            field=models.CharField(default='email@box.com', max_length=50),
        ),
        migrations.AddField(
            model_name='musician',
            name='login',
            field=models.CharField(default='login111', max_length=50),
        ),
        migrations.AddField(
            model_name='musician',
            name='password',
            field=models.CharField(default='password', max_length=30),
        ),
        migrations.AlterField(
            model_name='musician',
            name='group',
            field=models.ManyToManyField(null=True, through='gilp.Membership', to='gilp.MusicalGroup'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
