# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 10:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gilp', '0004_auto_20180108_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='musician',
            name='group',
        ),
        migrations.AlterField(
            model_name='membership',
            name='musician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Musician',
        ),
    ]
